Traceback (most recent call last):
  File "/home/barrow/PycharmProjects/helloWorldAgain/debugging_example.py", line 3, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
